language: node_js
node_js: "stable"
before_script:
      - git clone https://github.com/shexSpec/shex.js.git
      - cd shex.js
      - git checkout remote-query
      - npm install
script: ./bin/validate -x https://raw.githubusercontent.com/SuLab/Genewiki-ShEx/master/pathways/wikipathways/manifest_all.json --endpoint https://query.wikidata.org/bigdata/namespace/wdq/sparql --map '[{"node":"http://www.wikidata.org/entity/Q29496", "shape":"http://micel.io/genewiki/disease"}]'