language: node_js
node_js: "stable"
before_script: npm i shex
script: $(npm bin)/validate -x https://raw.githubusercontent.com/SuLab/Genewiki-ShEx/master/diseases/wikidata-disease-ontology.shex --endpoint https://query.wikidata.org/bigdata/namespace/wdq/sparql --map '[{"node":"http://www.wikidata.org/entity/Q29496", "shape":"http://micel.io/genewiki/disease"}]'